### ISSUE TITLE
Ineligible Repository

### ISSUE THREAD

**Issue by TijsDeBelie** [abxsantos/codekatas-TDD#3]
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

You added this to the discord but might not have setup the repository completely to accept submissions for this repository

**Comment by abxsantos** [comment]
Will do
